const $=id=>document.getElementById(id);
const worker=new Worker(new URL("./worker.js",import.meta.url),{type:"module"});
let config=null, operationId=0, currentFile=null, pendingFile=null, variables=[], previewRows=[], previewColumns=[], variableTypes=new Map(), sort={column:null,direction:1}, isBusy=true;
const formatBytes=n=>n>=1024**2?`${(n/1024**2).toFixed(n<10*1024**2?1:0)} MiB`:`${Math.ceil(n/1024)} KiB`;
function status(text,kind=""){ $("status").textContent=text; $("status").className=kind }
function busy(value){ isBusy=value; const disabled=value||!config; $("previewLimit").disabled=value||!currentFile; $("exportFormat").disabled=value||!currentFile; $("exportButton").disabled=value||!currentFile||currentFile.size>config.exportMaxBytes; $("filePicker").disabled=disabled; $("replaceFile").disabled=disabled; $("startOver").disabled=disabled; $("dropZone").classList.toggle("disabled",disabled); $("dropZone").setAttribute("aria-disabled",String(disabled)) }
function progress(m){ $("statusPanel").classList.add("has-progress");$("progressWrap").classList.remove("hidden"); const p=$("progress"); if(m.determinate&&m.total>0){p.max=m.total;p.value=m.current}else p.removeAttribute("value"); const labels={"wasm-download":"Downloading analysis engine","file-read":"Reading local file",metadata:"Reading metadata","preview-parse":"Parsing preview","preview-encode":"Encoding preview","export-parse":"Parsing export","export-encode":"Encoding export"}; $("progressText").textContent=`${labels[m.phase]||m.phase}${m.determinate&&m.total?` — ${Math.min(100,Math.round(m.current/m.total*100))}%`:""}` }
function clearProgress(){ $("progress").value=1;$("progress").max=1;$("progressText").textContent="";$("progressWrap").classList.add("hidden");$("statusPanel").classList.remove("has-progress") }

worker.onmessage=e=>{ const m=e.data; if(m.type==="ready"){config=m.config; setupConfig(); status("Ready — choose a SAS dataset");clearProgress();return} if(m.operationId!==operationId)return;
  if(m.type==="progress")progress(m); else if(m.type==="state"){busy(m.state!=="complete"); const labels={reading:"Reading the selected file…",metadata:"Inspecting metadata…",preview:"Building a bounded preview…",exporting:"Exporting the complete dataset…",complete:`Ready — ${currentFile?.name||"dataset"}`}; if(labels[m.state])status(labels[m.state]); if(m.state==="complete")clearProgress()}
  else if(m.type==="error"){status(m.message,"error");busy(false);clearProgress()} else if(m.type==="result"){if(m.kind==="metadata")renderMetadata(m.metadata);else if(m.kind==="preview")renderPreview(m.ndjson,m.rowLimit);else downloadExport(m)}
};
worker.onerror=()=>{status("The analysis worker stopped unexpectedly. Reload the page to try again.","error");clearProgress();busy(true)};
function setupConfig(){ $("pickLabel").classList.remove("disabled");$("policyText").textContent=`Recommended up to ${formatBytes(config.recommendedBytes)} · maximum ${formatBytes(config.hardMaxBytes)}`;$("exportPolicy").textContent=`Full export is limited to source files up to ${formatBytes(config.exportMaxBytes)} because the current exporter materializes both parsed data and the complete output in memory. Preview remains available for larger accepted files.`; for(const n of config.previewOptions){const o=new Option(n,n,n===config.defaultPreview,n===config.defaultPreview);$("previewLimit").add(o)} busy(false) }

function validateFile(file){
  if(!config)return; if(!file.name.toLowerCase().endsWith(".sas7bdat")){status("Choose a file ending in .sas7bdat.","error");return} if(file.size>config.hardMaxBytes){status(`${file.name} is ${formatBytes(file.size)} and exceeds the ${formatBytes(config.hardMaxBytes)} maximum.`,"error");return}
  return true;
}
function choose(file){
  if(!validateFile(file))return; if(currentFile){ pendingFile=file; $("replacementName").textContent=file.name; $("currentFileName").textContent=currentFile.name; $("replaceDialog").showModal(); return }
  loadFile(file);
}
function loadFile(file){
  setPreviewExpanded(false);currentFile=file; pendingFile=null; operationId++; variables=[]; previewRows=[]; variableTypes.clear(); $("variableSearch").value=""; ["summaryPanel","exportPanel","variablesPanel","previewPanel"].forEach(id=>$(id).classList.add("hidden"));
  $("dropZone").classList.add("hidden"); $("loadedFile").classList.remove("hidden"); $("statusPanel").classList.add("has-file"); $("loadedFileName").textContent=file.name; $("loadedFileDetails").textContent=`${formatBytes(file.size)} · Local browser session`;
  const warning=$("warning"); warning.classList.toggle("hidden",file.size<=config.recommendedBytes); warning.textContent=file.size>config.recommendedBytes?`Large file: ${formatBytes(file.size)} exceeds the recommended ${formatBytes(config.recommendedBytes)}. It may require substantial memory and take longer.`:"";
  status(`Reading ${file.name} locally…`);$("progress").removeAttribute("value");$("statusPanel").classList.add("has-progress");$("progressWrap").classList.remove("hidden");busy(true);worker.postMessage({type:"select",operationId,file,rowLimit:Number($("previewLimit").value)});
}
const zone=$("dropZone"), picker=$("filePicker"); picker.onchange=()=>picker.files[0]&&choose(picker.files[0]); zone.onclick=e=>{if(config&&e.target!==picker&&e.target.tagName!=="LABEL")picker.click()}; zone.onkeydown=e=>{if(config&&(e.key==="Enter"||e.key===" ")){e.preventDefault();picker.click()}};
for(const event of ["dragenter","dragover"]){zone.addEventListener(event,e=>{e.preventDefault();if(config&&!isBusy)zone.classList.add("drag")})} zone.ondragleave=()=>zone.classList.remove("drag");zone.ondrop=e=>{e.preventDefault();zone.classList.remove("drag");if(config&&!isBusy&&e.dataTransfer.files[0])choose(e.dataTransfer.files[0])};
$("replaceFile").onclick=()=>{picker.value="";picker.click()}; $("keepCurrent").onclick=()=>{pendingFile=null;picker.value="";$("replaceDialog").close()}; $("confirmReplace").onclick=()=>{const file=pendingFile;$("replaceDialog").close();if(file)loadFile(file)}; $("replaceDialog").oncancel=()=>{pendingFile=null;picker.value=""};
$("startOver").onclick=()=>{setPreviewExpanded(false);operationId++;worker.postMessage({type:"reset",operationId});currentFile=null;pendingFile=null;variables=[];previewRows=[];previewColumns=[];variableTypes.clear();picker.value="";$("variableSearch").value="";["summaryPanel","exportPanel","variablesPanel","previewPanel","loadedFile","warning"].forEach(id=>$(id).classList.add("hidden"));$("statusPanel").classList.remove("has-file");$("dropZone").classList.remove("hidden");status("Ready — choose a SAS dataset");clearProgress();busy(false)};

function value(v){return v===null||v===undefined||v===""?"—":String(v)}
function renderMetadata(meta){
  const entries=[["Rows",meta.row_count?.toLocaleString(),true],["Variables",meta.var_count?.toLocaleString(),true],["File size",formatBytes(currentFile.size),true],["Table",meta.table_name],["Encoding",meta.file_encoding],["Compression",meta.compression],["Endianness",meta.endianness],["Created",meta.creation_time],["Modified",meta.modified_time]];
  const dl=$("summary");dl.replaceChildren(...entries.map(([k,v,primary])=>{const d=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");if(primary)d.classList.add("metric-primary");dt.textContent=k;dd.textContent=value(v);d.append(dt,dd);return d}));
  variables=Object.entries(meta.vars||{}).sort((a,b)=>Number(a[0])-Number(b[0])).map(([,v])=>v); variableTypes=new Map(variables.map(v=>[v.var_name,typeInfo(v)]));renderVariables();$("summaryPanel").classList.remove("hidden");$("exportPanel").classList.remove("hidden");$("variablesPanel").classList.remove("hidden")
}
function typeInfo(v){const format=String(v.var_format_class||"").toLowerCase(),type=String(v.var_type||"").toLowerCase();if(format.startsWith("datetime"))return{kind:"datetime",label:"Datetime"};if(format==="date")return{kind:"date",label:"Date"};if(format.startsWith("time"))return{kind:"time",label:"Time"};if(type.includes("string")||String(v.var_type_class||"").toLowerCase()==="string")return{kind:"string",label:"String"};return{kind:"numeric",label:v.var_type||"Numeric"}}
function renderVariables(){const q=$("variableSearch").value.trim().toLowerCase(), fields=v=>{const info=typeInfo(v),storage=`${v.var_type||""}${v.var_type_class?` / ${v.var_type_class}`:""}`,semantic=info.kind==="numeric"||info.kind==="string"?storage:`${info.label} · ${storage}`;return[v.var_name,semantic,v.storage_width,v.var_label,v.var_format,v.display_width]}, filtered=variables.filter(v=>!q||fields(v).join(" ").toLowerCase().includes(q)); $("variableCount").textContent=q?`— ${filtered.length.toLocaleString()} of ${variables.length.toLocaleString()} variables`:`— ${variables.length.toLocaleString()} variables`; const rows=filtered.map(v=>{const tr=document.createElement("tr"),info=typeInfo(v);for(const [i,x] of fields(v).entries()){const td=document.createElement("td");td.textContent=value(x);td.title=x==null?"":String(x);if(i===0)td.classList.add("variable-name",`type-${info.kind}`);if(i===1){const badge=document.createElement("span");badge.classList.add("type-badge",`type-${info.kind}`);badge.textContent=info.label;td.replaceChildren(badge)}tr.append(td)}return tr});$("variables").replaceChildren(...rows)} $("variableSearch").oninput=renderVariables;

function renderPreview(ndjson,limit){previewRows=ndjson.split(/\r?\n/).filter(Boolean).map((line,i)=>{try{return JSON.parse(line)}catch{throw new Error(`Invalid preview data on line ${i+1}`)}});previewColumns=variables.length?variables.map(v=>v.var_name):[...new Set(previewRows.flatMap(Object.keys))];sort={column:null,direction:1};drawPreview();$("previewNote").textContent=`Showing ${previewRows.length.toLocaleString()} of up to ${Number(limit).toLocaleString()} rows · ${previewColumns.length.toLocaleString()} columns · Scroll horizontally to view all columns`;$("previewPanel").classList.remove("hidden")}
function drawPreview(){let rows=[...previewRows];if(sort.column){rows.sort((a,b)=>{const x=a[sort.column],y=b[sort.column];if(x==null)return y==null?0:1;if(y==null)return-1;return(typeof x==="number"&&typeof y==="number"?x-y:String(x).localeCompare(String(y),undefined,{numeric:true}))*sort.direction})} const hr=document.createElement("tr");for(const c of previewColumns){const info=variableTypes.get(c)||{kind:"numeric",label:"Unknown"},th=document.createElement("th"),b=document.createElement("button"),name=document.createElement("span"),type=document.createElement("small");th.classList.add("typed-header",`type-${info.kind}`);name.textContent=c+(sort.column===c?(sort.direction>0?" ▲":" ▼"):"");type.textContent=info.label;b.title=`Sort by ${c} (${info.label})`;b.onclick=()=>{sort=sort.column===c?{column:c,direction:-sort.direction}:{column:c,direction:1};drawPreview()};b.append(name,type);th.append(b);hr.append(th)}$("previewHead").replaceChildren(hr);$("previewBody").replaceChildren(...rows.map(row=>{const tr=document.createElement("tr");for(const c of previewColumns){const td=document.createElement("td");const x=row[c];td.textContent=x==null?"":typeof x==="object"?JSON.stringify(x):String(x);td.title=td.textContent;tr.append(td)}return tr}))}
function setPreviewExpanded(expanded){$("previewPanel").classList.toggle("expanded",expanded);document.body.classList.toggle("preview-expanded",expanded);$("expandPreview").textContent=expanded?"Exit expanded view":"Expand table";$("expandPreview").setAttribute("aria-expanded",String(expanded))}
$("expandPreview").onclick=()=>setPreviewExpanded(!$("previewPanel").classList.contains("expanded"));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("previewPanel").classList.contains("expanded"))setPreviewExpanded(false)});
$("previewLimit").onchange=()=>{if(!currentFile)return;operationId++;busy(true);worker.postMessage({type:"preview",operationId,rowLimit:Number($("previewLimit").value)})};
function downloadExport({output,filename,mime}){const url=URL.createObjectURL(new Blob([output],{type:mime})),link=document.createElement("a");link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status(`Downloaded ${filename}`)}
$("exportButton").onclick=()=>{if(!currentFile||isBusy)return;operationId++;busy(true);worker.postMessage({type:"export",operationId,format:$("exportFormat").value,sourceName:currentFile.name})};
