const $=id=>document.getElementById(id);
const worker=new Worker(new URL("./worker.js",import.meta.url),{type:"module"});
let config=null, operationId=0, currentFile=null, variables=[], previewRows=[], previewColumns=[], sort={column:null,direction:1};
const formatBytes=n=>n>=1024**2?`${(n/1024**2).toFixed(n<10*1024**2?1:0)} MiB`:`${Math.ceil(n/1024)} KiB`;
function status(text,kind=""){ $("status").textContent=text; $("status").className=kind }
function busy(value){ $("previewLimit").disabled=value||!currentFile; $("dropZone").classList.toggle("disabled",!config); $("dropZone").setAttribute("aria-disabled",String(!config)) }
function progress(m){ const p=$("progress"); if(m.determinate&&m.total>0){p.max=m.total;p.value=m.current}else p.removeAttribute("value"); const labels={"wasm-download":"Downloading analysis engine","file-read":"Reading local file",metadata:"Reading metadata","preview-parse":"Parsing preview","preview-encode":"Encoding preview"}; $("progressText").textContent=`${labels[m.phase]||m.phase}${m.determinate&&m.total?` — ${Math.min(100,Math.round(m.current/m.total*100))}%`:""}` }
function clearProgress(){ $("progress").value=1;$("progress").max=1;$("progressText").textContent="" }

worker.onmessage=e=>{ const m=e.data; if(m.type==="ready"){config=m.config; setupConfig(); status("Ready — choose a SAS dataset");clearProgress();return} if(m.operationId!==operationId)return;
  if(m.type==="progress")progress(m); else if(m.type==="state"){busy(m.state!=="complete"); const labels={reading:"Reading the selected file…",metadata:"Inspecting metadata…",preview:"Building a bounded preview…",complete:`Ready — ${currentFile?.name||"dataset"}`}; if(labels[m.state])status(labels[m.state]); if(m.state==="complete")clearProgress()}
  else if(m.type==="error"){status(m.message,"error");busy(false);clearProgress()} else if(m.type==="result"){if(m.kind==="metadata")renderMetadata(m.metadata);else renderPreview(m.ndjson,m.rowLimit)}
};
worker.onerror=()=>{status("The analysis worker stopped unexpectedly. Reload the page to try again.","error");busy(false)};
function setupConfig(){ $("filePicker").disabled=false;$("pickLabel").classList.remove("disabled");$("dropZone").classList.remove("disabled");$("dropZone").setAttribute("aria-disabled","false");$("policyText").textContent=`Recommended up to ${formatBytes(config.recommendedBytes)} · maximum ${formatBytes(config.hardMaxBytes)}`; for(const n of config.previewOptions){const o=new Option(n,n,n===config.defaultPreview,n===config.defaultPreview);$("previewLimit").add(o)} }

function choose(file){
  if(!config)return; if(!file.name.toLowerCase().endsWith(".sas7bdat")){status("Choose a file ending in .sas7bdat.","error");return} if(file.size>config.hardMaxBytes){status(`${file.name} is ${formatBytes(file.size)} and exceeds the ${formatBytes(config.hardMaxBytes)} maximum.`,"error");return}
  currentFile=file; operationId++; variables=[]; previewRows=[]; ["summaryPanel","variablesPanel","previewPanel"].forEach(id=>$(id).classList.add("hidden"));
  const warning=$("warning"); warning.classList.toggle("hidden",file.size<=config.recommendedBytes); warning.textContent=file.size>config.recommendedBytes?`Large file: ${formatBytes(file.size)} exceeds the recommended ${formatBytes(config.recommendedBytes)}. It may require substantial memory and take longer.`:"";
  status(`Reading ${file.name} locally…`);$("progress").removeAttribute("value");busy(true);worker.postMessage({type:"select",operationId,file,rowLimit:Number($("previewLimit").value)});
}
const zone=$("dropZone"), picker=$("filePicker"); picker.onchange=()=>picker.files[0]&&choose(picker.files[0]); zone.onclick=e=>{if(config&&e.target!==picker&&e.target.tagName!=="LABEL")picker.click()}; zone.onkeydown=e=>{if(config&&(e.key==="Enter"||e.key===" ")){e.preventDefault();picker.click()}};
for(const event of ["dragenter","dragover"]){zone.addEventListener(event,e=>{e.preventDefault();if(config)zone.classList.add("drag")})} zone.ondragleave=()=>zone.classList.remove("drag");zone.ondrop=e=>{e.preventDefault();zone.classList.remove("drag");if(config&&e.dataTransfer.files[0])choose(e.dataTransfer.files[0])};

function value(v){return v===null||v===undefined||v===""?"—":String(v)}
function renderMetadata(meta){
  $("fileDetails").textContent=`${currentFile.name} · ${formatBytes(currentFile.size)}`; const entries=[["Table",meta.table_name],["Rows",meta.row_count?.toLocaleString()],["Variables",meta.var_count?.toLocaleString()],["Encoding",meta.file_encoding],["Compression",meta.compression],["Endianness",meta.endianness],["Created",meta.creation_time],["Modified",meta.modified_time]];
  const dl=$("summary");dl.replaceChildren(...entries.map(([k,v])=>{const d=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=k;dd.textContent=value(v);d.append(dt,dd);return d}));
  variables=Object.entries(meta.vars||{}).sort((a,b)=>Number(a[0])-Number(b[0])).map(([,v])=>v); $("variableCount").textContent=`(${variables.length.toLocaleString()})`;renderVariables();$("summaryPanel").classList.remove("hidden");$("variablesPanel").classList.remove("hidden")
}
function renderVariables(){const q=$("variableSearch").value.trim().toLowerCase(), fields=v=>[v.var_name,`${v.var_type||""}${v.var_type_class?` / ${v.var_type_class}`:""}`,v.storage_width,v.var_label,v.var_format,v.display_width]; const rows=variables.filter(v=>!q||fields(v).join(" ").toLowerCase().includes(q)).map(v=>{const tr=document.createElement("tr");for(const x of fields(v)){const td=document.createElement("td");td.textContent=value(x);td.title=x==null?"":String(x);tr.append(td)}return tr});$("variables").replaceChildren(...rows)} $("variableSearch").oninput=renderVariables;

function renderPreview(ndjson,limit){previewRows=ndjson.split(/\r?\n/).filter(Boolean).map((line,i)=>{try{return JSON.parse(line)}catch{throw new Error(`Invalid preview data on line ${i+1}`)}});previewColumns=[...new Set(previewRows.flatMap(Object.keys))];sort={column:null,direction:1};drawPreview();$("previewNote").textContent=`Showing ${previewRows.length.toLocaleString()} of up to ${Number(limit).toLocaleString()} rows`;$("previewPanel").classList.remove("hidden")}
function drawPreview(){let rows=[...previewRows];if(sort.column){rows.sort((a,b)=>{const x=a[sort.column],y=b[sort.column];if(x==null)return y==null?0:1;if(y==null)return-1;return(typeof x==="number"&&typeof y==="number"?x-y:String(x).localeCompare(String(y),undefined,{numeric:true}))*sort.direction})} const hr=document.createElement("tr");for(const c of previewColumns){const th=document.createElement("th"),b=document.createElement("button");b.textContent=c+(sort.column===c?(sort.direction>0?" ▲":" ▼"):"");b.title=`Sort by ${c}`;b.onclick=()=>{sort=sort.column===c?{column:c,direction:-sort.direction}:{column:c,direction:1};drawPreview()};th.append(b);hr.append(th)}$("previewHead").replaceChildren(hr);$("previewBody").replaceChildren(...rows.map(row=>{const tr=document.createElement("tr");for(const c of previewColumns){const td=document.createElement("td");const x=row[c];td.textContent=x==null?"":typeof x==="object"?JSON.stringify(x):String(x);td.title=td.textContent;tr.append(td)}return tr}))}
$("previewLimit").onchange=()=>{if(!currentFile)return;operationId++;busy(true);worker.postMessage({type:"preview",operationId,rowLimit:Number($("previewLimit").value)})};
