[package]
name = "readstat"
version = "0.1.0"
authors = ["Curtis Alexander <calex@calex.org>"]
edition = "2018"
description = "Rust wrapper of the ReadStat C library"
license = "MIT"
repository = "https://github.com/curtisalexander/readstat-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dunce = "1.0"
readstat-sys = { path = "../readstat-sys", version = "0.1.0" }
structopt = "0.3"
thiserror = "1.0"
