/* automatically generated by rust-bindgen 0.72.1 */

pub type iconv_t = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    #[doc = "@brief Allocate descriptor for character set conversion\n@details The iconv_open function allocates a conversion descriptor suitable for converting byte sequences from character encoding fromcode to character encoding tocode.\n@param[in] tocode Target encoding\n@param[in] fromcode Source encoding\n@return The iconv_open() function returns a freshly allocated conversion descriptor. In case of error, it sets errno and returns (iconv_t)-1."]
    pub fn iconv_open(
        tocode: *const ::std::os::raw::c_char,
        fromcode: *const ::std::os::raw::c_char,
    ) -> iconv_t;
}
unsafe extern "C" {
    #[doc = "@brief Deallocate descriptor for character set conversion\n@details The iconv_close function deallocates a conversion descriptor cd previously allocated using iconv_open.\n@return When successful, the iconv_close function returns 0. In case of error, it sets errno and returns -1."]
    pub fn iconv_close(cd: iconv_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = "@brief Perform character set conversion\n@details The iconv function converts a sequence of characters in one character encoding to a sequence of characters in another character encoding.\n@param[in] cd A conversion descriptor, previously created by a call to iconv_open\n@param[in] inbuf The inbuf argument is the address of a variable that points to the first character of the input sequence\n@param[in] inbytesleft Number of bytes in inbuf buffer\n@param[in] outbuf The outbuf argument is the address of a variable that points to the first byte available in the output buffer\n@param[in] outbytesleft Number of bytes in outbuf buffer\n@returns The iconv function returns the number of characters converted in a nonreversible way during this call; reversible conversions are not counted. In case of error, it sets errno and returns (size_t)-1."]
    pub fn iconv(
        cd: iconv_t,
        inbuf: *mut *const ::std::os::raw::c_char,
        inbytesleft: *mut usize,
        outbuf: *mut *mut ::std::os::raw::c_char,
        outbytesleft: *mut usize,
    ) -> usize;
}
