/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val { byte | mask } else { byte & !mask }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_off_t = __int64_t;
pub type off_t = __darwin_off_t;
pub type time_t = __darwin_time_t;
pub const readstat_type_e_READSTAT_TYPE_STRING: readstat_type_e = 0;
pub const readstat_type_e_READSTAT_TYPE_INT8: readstat_type_e = 1;
pub const readstat_type_e_READSTAT_TYPE_INT16: readstat_type_e = 2;
pub const readstat_type_e_READSTAT_TYPE_INT32: readstat_type_e = 3;
pub const readstat_type_e_READSTAT_TYPE_FLOAT: readstat_type_e = 4;
pub const readstat_type_e_READSTAT_TYPE_DOUBLE: readstat_type_e = 5;
pub const readstat_type_e_READSTAT_TYPE_STRING_REF: readstat_type_e = 6;
pub type readstat_type_e = ::std::os::raw::c_uint;
pub use self::readstat_type_e as readstat_type_t;
pub const readstat_type_class_e_READSTAT_TYPE_CLASS_STRING: readstat_type_class_e = 0;
pub const readstat_type_class_e_READSTAT_TYPE_CLASS_NUMERIC: readstat_type_class_e = 1;
pub type readstat_type_class_e = ::std::os::raw::c_uint;
pub use self::readstat_type_class_e as readstat_type_class_t;
pub const readstat_measure_e_READSTAT_MEASURE_UNKNOWN: readstat_measure_e = 0;
pub const readstat_measure_e_READSTAT_MEASURE_NOMINAL: readstat_measure_e = 1;
pub const readstat_measure_e_READSTAT_MEASURE_ORDINAL: readstat_measure_e = 2;
pub const readstat_measure_e_READSTAT_MEASURE_SCALE: readstat_measure_e = 3;
pub type readstat_measure_e = ::std::os::raw::c_uint;
pub use self::readstat_measure_e as readstat_measure_t;
pub const readstat_alignment_e_READSTAT_ALIGNMENT_UNKNOWN: readstat_alignment_e = 0;
pub const readstat_alignment_e_READSTAT_ALIGNMENT_LEFT: readstat_alignment_e = 1;
pub const readstat_alignment_e_READSTAT_ALIGNMENT_CENTER: readstat_alignment_e = 2;
pub const readstat_alignment_e_READSTAT_ALIGNMENT_RIGHT: readstat_alignment_e = 3;
pub type readstat_alignment_e = ::std::os::raw::c_uint;
pub use self::readstat_alignment_e as readstat_alignment_t;
pub const readstat_compress_e_READSTAT_COMPRESS_NONE: readstat_compress_e = 0;
pub const readstat_compress_e_READSTAT_COMPRESS_ROWS: readstat_compress_e = 1;
pub const readstat_compress_e_READSTAT_COMPRESS_BINARY: readstat_compress_e = 2;
pub type readstat_compress_e = ::std::os::raw::c_uint;
pub use self::readstat_compress_e as readstat_compress_t;
pub const readstat_endian_e_READSTAT_ENDIAN_NONE: readstat_endian_e = 0;
pub const readstat_endian_e_READSTAT_ENDIAN_LITTLE: readstat_endian_e = 1;
pub const readstat_endian_e_READSTAT_ENDIAN_BIG: readstat_endian_e = 2;
pub type readstat_endian_e = ::std::os::raw::c_uint;
pub use self::readstat_endian_e as readstat_endian_t;
pub const readstat_error_e_READSTAT_OK: readstat_error_e = 0;
pub const readstat_error_e_READSTAT_ERROR_OPEN: readstat_error_e = 1;
pub const readstat_error_e_READSTAT_ERROR_READ: readstat_error_e = 2;
pub const readstat_error_e_READSTAT_ERROR_MALLOC: readstat_error_e = 3;
pub const readstat_error_e_READSTAT_ERROR_USER_ABORT: readstat_error_e = 4;
pub const readstat_error_e_READSTAT_ERROR_PARSE: readstat_error_e = 5;
pub const readstat_error_e_READSTAT_ERROR_UNSUPPORTED_COMPRESSION: readstat_error_e = 6;
pub const readstat_error_e_READSTAT_ERROR_UNSUPPORTED_CHARSET: readstat_error_e = 7;
pub const readstat_error_e_READSTAT_ERROR_COLUMN_COUNT_MISMATCH: readstat_error_e = 8;
pub const readstat_error_e_READSTAT_ERROR_ROW_COUNT_MISMATCH: readstat_error_e = 9;
pub const readstat_error_e_READSTAT_ERROR_ROW_WIDTH_MISMATCH: readstat_error_e = 10;
pub const readstat_error_e_READSTAT_ERROR_BAD_FORMAT_STRING: readstat_error_e = 11;
pub const readstat_error_e_READSTAT_ERROR_VALUE_TYPE_MISMATCH: readstat_error_e = 12;
pub const readstat_error_e_READSTAT_ERROR_WRITE: readstat_error_e = 13;
pub const readstat_error_e_READSTAT_ERROR_WRITER_NOT_INITIALIZED: readstat_error_e = 14;
pub const readstat_error_e_READSTAT_ERROR_SEEK: readstat_error_e = 15;
pub const readstat_error_e_READSTAT_ERROR_CONVERT: readstat_error_e = 16;
pub const readstat_error_e_READSTAT_ERROR_CONVERT_BAD_STRING: readstat_error_e = 17;
pub const readstat_error_e_READSTAT_ERROR_CONVERT_SHORT_STRING: readstat_error_e = 18;
pub const readstat_error_e_READSTAT_ERROR_CONVERT_LONG_STRING: readstat_error_e = 19;
pub const readstat_error_e_READSTAT_ERROR_NUMERIC_VALUE_IS_OUT_OF_RANGE: readstat_error_e = 20;
pub const readstat_error_e_READSTAT_ERROR_TAGGED_VALUE_IS_OUT_OF_RANGE: readstat_error_e = 21;
pub const readstat_error_e_READSTAT_ERROR_STRING_VALUE_IS_TOO_LONG: readstat_error_e = 22;
pub const readstat_error_e_READSTAT_ERROR_TAGGED_VALUES_NOT_SUPPORTED: readstat_error_e = 23;
pub const readstat_error_e_READSTAT_ERROR_UNSUPPORTED_FILE_FORMAT_VERSION: readstat_error_e = 24;
pub const readstat_error_e_READSTAT_ERROR_NAME_BEGINS_WITH_ILLEGAL_CHARACTER: readstat_error_e = 25;
pub const readstat_error_e_READSTAT_ERROR_NAME_CONTAINS_ILLEGAL_CHARACTER: readstat_error_e = 26;
pub const readstat_error_e_READSTAT_ERROR_NAME_IS_RESERVED_WORD: readstat_error_e = 27;
pub const readstat_error_e_READSTAT_ERROR_NAME_IS_TOO_LONG: readstat_error_e = 28;
pub const readstat_error_e_READSTAT_ERROR_BAD_TIMESTAMP_STRING: readstat_error_e = 29;
pub const readstat_error_e_READSTAT_ERROR_BAD_FREQUENCY_WEIGHT: readstat_error_e = 30;
pub const readstat_error_e_READSTAT_ERROR_TOO_MANY_MISSING_VALUE_DEFINITIONS: readstat_error_e = 31;
pub const readstat_error_e_READSTAT_ERROR_NOTE_IS_TOO_LONG: readstat_error_e = 32;
pub const readstat_error_e_READSTAT_ERROR_STRING_REFS_NOT_SUPPORTED: readstat_error_e = 33;
pub const readstat_error_e_READSTAT_ERROR_STRING_REF_IS_REQUIRED: readstat_error_e = 34;
pub const readstat_error_e_READSTAT_ERROR_ROW_IS_TOO_WIDE_FOR_PAGE: readstat_error_e = 35;
pub const readstat_error_e_READSTAT_ERROR_TOO_FEW_COLUMNS: readstat_error_e = 36;
pub const readstat_error_e_READSTAT_ERROR_TOO_MANY_COLUMNS: readstat_error_e = 37;
pub const readstat_error_e_READSTAT_ERROR_NAME_IS_ZERO_LENGTH: readstat_error_e = 38;
pub const readstat_error_e_READSTAT_ERROR_BAD_TIMESTAMP_VALUE: readstat_error_e = 39;
pub const readstat_error_e_READSTAT_ERROR_BAD_MR_STRING: readstat_error_e = 40;
pub type readstat_error_e = ::std::os::raw::c_uint;
pub use self::readstat_error_e as readstat_error_t;
unsafe extern "C" {
    pub fn readstat_error_message(error_code: readstat_error_t) -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mr_set_s {
    pub type_: ::std::os::raw::c_char,
    pub name: *mut ::std::os::raw::c_char,
    pub label: *mut ::std::os::raw::c_char,
    pub is_dichotomy: ::std::os::raw::c_int,
    pub counted_value: ::std::os::raw::c_int,
    pub subvariables: *mut *mut ::std::os::raw::c_char,
    pub num_subvars: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mr_set_s"][::std::mem::size_of::<mr_set_s>() - 48usize];
    ["Alignment of mr_set_s"][::std::mem::align_of::<mr_set_s>() - 8usize];
    ["Offset of field: mr_set_s::type_"][::std::mem::offset_of!(mr_set_s, type_) - 0usize];
    ["Offset of field: mr_set_s::name"][::std::mem::offset_of!(mr_set_s, name) - 8usize];
    ["Offset of field: mr_set_s::label"][::std::mem::offset_of!(mr_set_s, label) - 16usize];
    ["Offset of field: mr_set_s::is_dichotomy"]
        [::std::mem::offset_of!(mr_set_s, is_dichotomy) - 24usize];
    ["Offset of field: mr_set_s::counted_value"]
        [::std::mem::offset_of!(mr_set_s, counted_value) - 28usize];
    ["Offset of field: mr_set_s::subvariables"]
        [::std::mem::offset_of!(mr_set_s, subvariables) - 32usize];
    ["Offset of field: mr_set_s::num_subvars"]
        [::std::mem::offset_of!(mr_set_s, num_subvars) - 40usize];
};
pub type mr_set_t = mr_set_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_metadata_s {
    pub row_count: i64,
    pub var_count: i64,
    pub creation_time: time_t,
    pub modified_time: time_t,
    pub file_format_version: i64,
    pub compression: readstat_compress_t,
    pub endianness: readstat_endian_t,
    pub table_name: *const ::std::os::raw::c_char,
    pub file_label: *const ::std::os::raw::c_char,
    pub file_encoding: *const ::std::os::raw::c_char,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub multiple_response_sets_length: usize,
    pub mr_sets: *mut mr_set_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_metadata_s"][::std::mem::size_of::<readstat_metadata_s>() - 96usize];
    ["Alignment of readstat_metadata_s"][::std::mem::align_of::<readstat_metadata_s>() - 8usize];
    ["Offset of field: readstat_metadata_s::row_count"]
        [::std::mem::offset_of!(readstat_metadata_s, row_count) - 0usize];
    ["Offset of field: readstat_metadata_s::var_count"]
        [::std::mem::offset_of!(readstat_metadata_s, var_count) - 8usize];
    ["Offset of field: readstat_metadata_s::creation_time"]
        [::std::mem::offset_of!(readstat_metadata_s, creation_time) - 16usize];
    ["Offset of field: readstat_metadata_s::modified_time"]
        [::std::mem::offset_of!(readstat_metadata_s, modified_time) - 24usize];
    ["Offset of field: readstat_metadata_s::file_format_version"]
        [::std::mem::offset_of!(readstat_metadata_s, file_format_version) - 32usize];
    ["Offset of field: readstat_metadata_s::compression"]
        [::std::mem::offset_of!(readstat_metadata_s, compression) - 40usize];
    ["Offset of field: readstat_metadata_s::endianness"]
        [::std::mem::offset_of!(readstat_metadata_s, endianness) - 44usize];
    ["Offset of field: readstat_metadata_s::table_name"]
        [::std::mem::offset_of!(readstat_metadata_s, table_name) - 48usize];
    ["Offset of field: readstat_metadata_s::file_label"]
        [::std::mem::offset_of!(readstat_metadata_s, file_label) - 56usize];
    ["Offset of field: readstat_metadata_s::file_encoding"]
        [::std::mem::offset_of!(readstat_metadata_s, file_encoding) - 64usize];
    ["Offset of field: readstat_metadata_s::multiple_response_sets_length"]
        [::std::mem::offset_of!(readstat_metadata_s, multiple_response_sets_length) - 80usize];
    ["Offset of field: readstat_metadata_s::mr_sets"]
        [::std::mem::offset_of!(readstat_metadata_s, mr_sets) - 88usize];
};
impl readstat_metadata_s {
    #[inline]
    pub fn is64bit(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_is64bit(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn is64bit_raw(this: *const Self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                1u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_is64bit_raw(this: *mut Self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(is64bit: ::std::os::raw::c_uint) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let is64bit: u32 = unsafe { ::std::mem::transmute(is64bit) };
            is64bit as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type readstat_metadata_t = readstat_metadata_s;
unsafe extern "C" {
    pub fn readstat_get_row_count(metadata: *mut readstat_metadata_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_get_var_count(metadata: *mut readstat_metadata_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_get_creation_time(metadata: *mut readstat_metadata_t) -> time_t;
}
unsafe extern "C" {
    pub fn readstat_get_modified_time(metadata: *mut readstat_metadata_t) -> time_t;
}
unsafe extern "C" {
    pub fn readstat_get_file_format_version(
        metadata: *mut readstat_metadata_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_get_file_format_is_64bit(
        metadata: *mut readstat_metadata_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_get_compression(metadata: *mut readstat_metadata_t) -> readstat_compress_t;
}
unsafe extern "C" {
    pub fn readstat_get_endianness(metadata: *mut readstat_metadata_t) -> readstat_endian_t;
}
unsafe extern "C" {
    pub fn readstat_get_table_name(
        metadata: *mut readstat_metadata_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn readstat_get_file_label(
        metadata: *mut readstat_metadata_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn readstat_get_file_encoding(
        metadata: *mut readstat_metadata_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn readstat_get_multiple_response_sets(
        metadata: *mut readstat_metadata_t,
    ) -> *const mr_set_t;
}
unsafe extern "C" {
    pub fn readstat_get_multiple_response_sets_length(metadata: *mut readstat_metadata_t) -> usize;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct readstat_value_s {
    pub v: readstat_value_s__bindgen_ty_1,
    pub type_: readstat_type_t,
    pub tag: ::std::os::raw::c_char,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub __bindgen_padding_0: u16,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union readstat_value_s__bindgen_ty_1 {
    pub float_value: f32,
    pub double_value: f64,
    pub i8_value: i8,
    pub i16_value: i16,
    pub i32_value: i32,
    pub string_value: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_value_s__bindgen_ty_1"]
        [::std::mem::size_of::<readstat_value_s__bindgen_ty_1>() - 8usize];
    ["Alignment of readstat_value_s__bindgen_ty_1"]
        [::std::mem::align_of::<readstat_value_s__bindgen_ty_1>() - 8usize];
    ["Offset of field: readstat_value_s__bindgen_ty_1::float_value"]
        [::std::mem::offset_of!(readstat_value_s__bindgen_ty_1, float_value) - 0usize];
    ["Offset of field: readstat_value_s__bindgen_ty_1::double_value"]
        [::std::mem::offset_of!(readstat_value_s__bindgen_ty_1, double_value) - 0usize];
    ["Offset of field: readstat_value_s__bindgen_ty_1::i8_value"]
        [::std::mem::offset_of!(readstat_value_s__bindgen_ty_1, i8_value) - 0usize];
    ["Offset of field: readstat_value_s__bindgen_ty_1::i16_value"]
        [::std::mem::offset_of!(readstat_value_s__bindgen_ty_1, i16_value) - 0usize];
    ["Offset of field: readstat_value_s__bindgen_ty_1::i32_value"]
        [::std::mem::offset_of!(readstat_value_s__bindgen_ty_1, i32_value) - 0usize];
    ["Offset of field: readstat_value_s__bindgen_ty_1::string_value"]
        [::std::mem::offset_of!(readstat_value_s__bindgen_ty_1, string_value) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_value_s"][::std::mem::size_of::<readstat_value_s>() - 16usize];
    ["Alignment of readstat_value_s"][::std::mem::align_of::<readstat_value_s>() - 8usize];
    ["Offset of field: readstat_value_s::v"][::std::mem::offset_of!(readstat_value_s, v) - 0usize];
    ["Offset of field: readstat_value_s::type_"]
        [::std::mem::offset_of!(readstat_value_s, type_) - 8usize];
    ["Offset of field: readstat_value_s::tag"]
        [::std::mem::offset_of!(readstat_value_s, tag) - 12usize];
};
impl readstat_value_s {
    #[inline]
    pub fn is_system_missing(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_is_system_missing(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn is_system_missing_raw(this: *const Self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                1u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_is_system_missing_raw(this: *mut Self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn is_tagged_missing(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(1usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_is_tagged_missing(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(1usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn is_tagged_missing_raw(this: *const Self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                1usize,
                1u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_is_tagged_missing_raw(this: *mut Self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                1usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        is_system_missing: ::std::os::raw::c_uint,
        is_tagged_missing: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let is_system_missing: u32 = unsafe { ::std::mem::transmute(is_system_missing) };
            is_system_missing as u64
        });
        __bindgen_bitfield_unit.set(1usize, 1u8, {
            let is_tagged_missing: u32 = unsafe { ::std::mem::transmute(is_tagged_missing) };
            is_tagged_missing as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type readstat_value_t = readstat_value_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_value_label_s {
    pub double_key: f64,
    pub int32_key: i32,
    pub tag: ::std::os::raw::c_char,
    pub string_key: *mut ::std::os::raw::c_char,
    pub string_key_len: usize,
    pub label: *mut ::std::os::raw::c_char,
    pub label_len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_value_label_s"][::std::mem::size_of::<readstat_value_label_s>() - 48usize];
    ["Alignment of readstat_value_label_s"]
        [::std::mem::align_of::<readstat_value_label_s>() - 8usize];
    ["Offset of field: readstat_value_label_s::double_key"]
        [::std::mem::offset_of!(readstat_value_label_s, double_key) - 0usize];
    ["Offset of field: readstat_value_label_s::int32_key"]
        [::std::mem::offset_of!(readstat_value_label_s, int32_key) - 8usize];
    ["Offset of field: readstat_value_label_s::tag"]
        [::std::mem::offset_of!(readstat_value_label_s, tag) - 12usize];
    ["Offset of field: readstat_value_label_s::string_key"]
        [::std::mem::offset_of!(readstat_value_label_s, string_key) - 16usize];
    ["Offset of field: readstat_value_label_s::string_key_len"]
        [::std::mem::offset_of!(readstat_value_label_s, string_key_len) - 24usize];
    ["Offset of field: readstat_value_label_s::label"]
        [::std::mem::offset_of!(readstat_value_label_s, label) - 32usize];
    ["Offset of field: readstat_value_label_s::label_len"]
        [::std::mem::offset_of!(readstat_value_label_s, label_len) - 40usize];
};
pub type readstat_value_label_t = readstat_value_label_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_label_set_s {
    pub type_: readstat_type_t,
    pub name: [::std::os::raw::c_char; 256usize],
    pub value_labels: *mut readstat_value_label_t,
    pub value_labels_count: ::std::os::raw::c_long,
    pub value_labels_capacity: ::std::os::raw::c_long,
    pub variables: *mut ::std::os::raw::c_void,
    pub variables_count: ::std::os::raw::c_long,
    pub variables_capacity: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_label_set_s"][::std::mem::size_of::<readstat_label_set_s>() - 312usize];
    ["Alignment of readstat_label_set_s"][::std::mem::align_of::<readstat_label_set_s>() - 8usize];
    ["Offset of field: readstat_label_set_s::type_"]
        [::std::mem::offset_of!(readstat_label_set_s, type_) - 0usize];
    ["Offset of field: readstat_label_set_s::name"]
        [::std::mem::offset_of!(readstat_label_set_s, name) - 4usize];
    ["Offset of field: readstat_label_set_s::value_labels"]
        [::std::mem::offset_of!(readstat_label_set_s, value_labels) - 264usize];
    ["Offset of field: readstat_label_set_s::value_labels_count"]
        [::std::mem::offset_of!(readstat_label_set_s, value_labels_count) - 272usize];
    ["Offset of field: readstat_label_set_s::value_labels_capacity"]
        [::std::mem::offset_of!(readstat_label_set_s, value_labels_capacity) - 280usize];
    ["Offset of field: readstat_label_set_s::variables"]
        [::std::mem::offset_of!(readstat_label_set_s, variables) - 288usize];
    ["Offset of field: readstat_label_set_s::variables_count"]
        [::std::mem::offset_of!(readstat_label_set_s, variables_count) - 296usize];
    ["Offset of field: readstat_label_set_s::variables_capacity"]
        [::std::mem::offset_of!(readstat_label_set_s, variables_capacity) - 304usize];
};
pub type readstat_label_set_t = readstat_label_set_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct readstat_missingness_s {
    pub missing_ranges: [readstat_value_t; 32usize],
    pub missing_ranges_count: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_missingness_s"][::std::mem::size_of::<readstat_missingness_s>() - 520usize];
    ["Alignment of readstat_missingness_s"]
        [::std::mem::align_of::<readstat_missingness_s>() - 8usize];
    ["Offset of field: readstat_missingness_s::missing_ranges"]
        [::std::mem::offset_of!(readstat_missingness_s, missing_ranges) - 0usize];
    ["Offset of field: readstat_missingness_s::missing_ranges_count"]
        [::std::mem::offset_of!(readstat_missingness_s, missing_ranges_count) - 512usize];
};
pub type readstat_missingness_t = readstat_missingness_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct readstat_variable_s {
    pub type_: readstat_type_t,
    pub index: ::std::os::raw::c_int,
    pub name: [::std::os::raw::c_char; 300usize],
    pub format: [::std::os::raw::c_char; 256usize],
    pub label: [::std::os::raw::c_char; 1024usize],
    pub label_set: *mut readstat_label_set_t,
    pub offset: off_t,
    pub storage_width: usize,
    pub user_width: usize,
    pub missingness: readstat_missingness_t,
    pub measure: readstat_measure_t,
    pub alignment: readstat_alignment_t,
    pub display_width: ::std::os::raw::c_int,
    pub decimals: ::std::os::raw::c_int,
    pub skip: ::std::os::raw::c_int,
    pub index_after_skipping: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_variable_s"][::std::mem::size_of::<readstat_variable_s>() - 2168usize];
    ["Alignment of readstat_variable_s"][::std::mem::align_of::<readstat_variable_s>() - 8usize];
    ["Offset of field: readstat_variable_s::type_"]
        [::std::mem::offset_of!(readstat_variable_s, type_) - 0usize];
    ["Offset of field: readstat_variable_s::index"]
        [::std::mem::offset_of!(readstat_variable_s, index) - 4usize];
    ["Offset of field: readstat_variable_s::name"]
        [::std::mem::offset_of!(readstat_variable_s, name) - 8usize];
    ["Offset of field: readstat_variable_s::format"]
        [::std::mem::offset_of!(readstat_variable_s, format) - 308usize];
    ["Offset of field: readstat_variable_s::label"]
        [::std::mem::offset_of!(readstat_variable_s, label) - 564usize];
    ["Offset of field: readstat_variable_s::label_set"]
        [::std::mem::offset_of!(readstat_variable_s, label_set) - 1592usize];
    ["Offset of field: readstat_variable_s::offset"]
        [::std::mem::offset_of!(readstat_variable_s, offset) - 1600usize];
    ["Offset of field: readstat_variable_s::storage_width"]
        [::std::mem::offset_of!(readstat_variable_s, storage_width) - 1608usize];
    ["Offset of field: readstat_variable_s::user_width"]
        [::std::mem::offset_of!(readstat_variable_s, user_width) - 1616usize];
    ["Offset of field: readstat_variable_s::missingness"]
        [::std::mem::offset_of!(readstat_variable_s, missingness) - 1624usize];
    ["Offset of field: readstat_variable_s::measure"]
        [::std::mem::offset_of!(readstat_variable_s, measure) - 2144usize];
    ["Offset of field: readstat_variable_s::alignment"]
        [::std::mem::offset_of!(readstat_variable_s, alignment) - 2148usize];
    ["Offset of field: readstat_variable_s::display_width"]
        [::std::mem::offset_of!(readstat_variable_s, display_width) - 2152usize];
    ["Offset of field: readstat_variable_s::decimals"]
        [::std::mem::offset_of!(readstat_variable_s, decimals) - 2156usize];
    ["Offset of field: readstat_variable_s::skip"]
        [::std::mem::offset_of!(readstat_variable_s, skip) - 2160usize];
    ["Offset of field: readstat_variable_s::index_after_skipping"]
        [::std::mem::offset_of!(readstat_variable_s, index_after_skipping) - 2164usize];
};
pub type readstat_variable_t = readstat_variable_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct readstat_schema_entry_s {
    pub row: u32,
    pub col: u32,
    pub len: u32,
    pub skip: ::std::os::raw::c_int,
    pub variable: readstat_variable_t,
    pub labelset: [::std::os::raw::c_char; 32usize],
    pub decimal_separator: ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_schema_entry_s"]
        [::std::mem::size_of::<readstat_schema_entry_s>() - 2224usize];
    ["Alignment of readstat_schema_entry_s"]
        [::std::mem::align_of::<readstat_schema_entry_s>() - 8usize];
    ["Offset of field: readstat_schema_entry_s::row"]
        [::std::mem::offset_of!(readstat_schema_entry_s, row) - 0usize];
    ["Offset of field: readstat_schema_entry_s::col"]
        [::std::mem::offset_of!(readstat_schema_entry_s, col) - 4usize];
    ["Offset of field: readstat_schema_entry_s::len"]
        [::std::mem::offset_of!(readstat_schema_entry_s, len) - 8usize];
    ["Offset of field: readstat_schema_entry_s::skip"]
        [::std::mem::offset_of!(readstat_schema_entry_s, skip) - 12usize];
    ["Offset of field: readstat_schema_entry_s::variable"]
        [::std::mem::offset_of!(readstat_schema_entry_s, variable) - 16usize];
    ["Offset of field: readstat_schema_entry_s::labelset"]
        [::std::mem::offset_of!(readstat_schema_entry_s, labelset) - 2184usize];
    ["Offset of field: readstat_schema_entry_s::decimal_separator"]
        [::std::mem::offset_of!(readstat_schema_entry_s, decimal_separator) - 2216usize];
};
pub type readstat_schema_entry_t = readstat_schema_entry_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_schema_s {
    pub filename: [::std::os::raw::c_char; 255usize],
    pub rows_per_observation: u32,
    pub cols_per_observation: u32,
    pub first_line: ::std::os::raw::c_int,
    pub entry_count: ::std::os::raw::c_int,
    pub field_delimiter: ::std::os::raw::c_char,
    pub entries: *mut readstat_schema_entry_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_schema_s"][::std::mem::size_of::<readstat_schema_s>() - 288usize];
    ["Alignment of readstat_schema_s"][::std::mem::align_of::<readstat_schema_s>() - 8usize];
    ["Offset of field: readstat_schema_s::filename"]
        [::std::mem::offset_of!(readstat_schema_s, filename) - 0usize];
    ["Offset of field: readstat_schema_s::rows_per_observation"]
        [::std::mem::offset_of!(readstat_schema_s, rows_per_observation) - 256usize];
    ["Offset of field: readstat_schema_s::cols_per_observation"]
        [::std::mem::offset_of!(readstat_schema_s, cols_per_observation) - 260usize];
    ["Offset of field: readstat_schema_s::first_line"]
        [::std::mem::offset_of!(readstat_schema_s, first_line) - 264usize];
    ["Offset of field: readstat_schema_s::entry_count"]
        [::std::mem::offset_of!(readstat_schema_s, entry_count) - 268usize];
    ["Offset of field: readstat_schema_s::field_delimiter"]
        [::std::mem::offset_of!(readstat_schema_s, field_delimiter) - 272usize];
    ["Offset of field: readstat_schema_s::entries"]
        [::std::mem::offset_of!(readstat_schema_s, entries) - 280usize];
};
pub type readstat_schema_t = readstat_schema_s;
unsafe extern "C" {
    pub fn readstat_value_type(value: readstat_value_t) -> readstat_type_t;
}
unsafe extern "C" {
    pub fn readstat_value_type_class(value: readstat_value_t) -> readstat_type_class_t;
}
unsafe extern "C" {
    pub fn readstat_value_is_missing(
        value: readstat_value_t,
        variable: *mut readstat_variable_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_value_is_system_missing(value: readstat_value_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_value_is_tagged_missing(value: readstat_value_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_value_is_defined_missing(
        value: readstat_value_t,
        variable: *mut readstat_variable_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_value_tag(value: readstat_value_t) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn readstat_int8_value(value: readstat_value_t) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn readstat_int16_value(value: readstat_value_t) -> i16;
}
unsafe extern "C" {
    pub fn readstat_int32_value(value: readstat_value_t) -> i32;
}
unsafe extern "C" {
    pub fn readstat_float_value(value: readstat_value_t) -> f32;
}
unsafe extern "C" {
    pub fn readstat_double_value(value: readstat_value_t) -> f64;
}
unsafe extern "C" {
    pub fn readstat_string_value(value: readstat_value_t) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn readstat_type_class(type_: readstat_type_t) -> readstat_type_class_t;
}
unsafe extern "C" {
    pub fn readstat_variable_get_index(
        variable: *const readstat_variable_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_variable_get_index_after_skipping(
        variable: *const readstat_variable_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_variable_get_name(
        variable: *const readstat_variable_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn readstat_variable_get_label(
        variable: *const readstat_variable_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn readstat_variable_get_format(
        variable: *const readstat_variable_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn readstat_variable_get_type(variable: *const readstat_variable_t) -> readstat_type_t;
}
unsafe extern "C" {
    pub fn readstat_variable_get_type_class(
        variable: *const readstat_variable_t,
    ) -> readstat_type_class_t;
}
unsafe extern "C" {
    pub fn readstat_variable_get_storage_width(variable: *const readstat_variable_t) -> usize;
}
unsafe extern "C" {
    pub fn readstat_variable_get_display_width(
        variable: *const readstat_variable_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_variable_get_measure(
        variable: *const readstat_variable_t,
    ) -> readstat_measure_t;
}
unsafe extern "C" {
    pub fn readstat_variable_get_alignment(
        variable: *const readstat_variable_t,
    ) -> readstat_alignment_t;
}
unsafe extern "C" {
    pub fn readstat_variable_get_missing_ranges_count(
        variable: *const readstat_variable_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn readstat_variable_get_missing_range_lo(
        variable: *const readstat_variable_t,
        i: ::std::os::raw::c_int,
    ) -> readstat_value_t;
}
unsafe extern "C" {
    pub fn readstat_variable_get_missing_range_hi(
        variable: *const readstat_variable_t,
        i: ::std::os::raw::c_int,
    ) -> readstat_value_t;
}
pub type readstat_metadata_handler = ::std::option::Option<
    unsafe extern "C" fn(
        metadata: *mut readstat_metadata_t,
        ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type readstat_note_handler = ::std::option::Option<
    unsafe extern "C" fn(
        note_index: ::std::os::raw::c_int,
        note: *const ::std::os::raw::c_char,
        ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type readstat_variable_handler = ::std::option::Option<
    unsafe extern "C" fn(
        index: ::std::os::raw::c_int,
        variable: *mut readstat_variable_t,
        val_labels: *const ::std::os::raw::c_char,
        ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type readstat_fweight_handler = ::std::option::Option<
    unsafe extern "C" fn(
        variable: *mut readstat_variable_t,
        ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type readstat_value_handler = ::std::option::Option<
    unsafe extern "C" fn(
        obs_index: ::std::os::raw::c_int,
        variable: *mut readstat_variable_t,
        value: readstat_value_t,
        ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type readstat_value_label_handler = ::std::option::Option<
    unsafe extern "C" fn(
        val_labels: *const ::std::os::raw::c_char,
        value: readstat_value_t,
        label: *const ::std::os::raw::c_char,
        ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type readstat_error_handler = ::std::option::Option<
    unsafe extern "C" fn(
        error_message: *const ::std::os::raw::c_char,
        ctx: *mut ::std::os::raw::c_void,
    ),
>;
pub type readstat_progress_handler = ::std::option::Option<
    unsafe extern "C" fn(progress: f64, ctx: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
>;
pub type readstat_off_t = off_t;
pub const readstat_io_flags_e_READSTAT_SEEK_SET: readstat_io_flags_e = 0;
pub const readstat_io_flags_e_READSTAT_SEEK_CUR: readstat_io_flags_e = 1;
pub const readstat_io_flags_e_READSTAT_SEEK_END: readstat_io_flags_e = 2;
pub type readstat_io_flags_e = ::std::os::raw::c_uint;
pub use self::readstat_io_flags_e as readstat_io_flags_t;
pub type readstat_open_handler = ::std::option::Option<
    unsafe extern "C" fn(
        path: *const ::std::os::raw::c_char,
        io_ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type readstat_close_handler = ::std::option::Option<
    unsafe extern "C" fn(io_ctx: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
>;
pub type readstat_seek_handler = ::std::option::Option<
    unsafe extern "C" fn(
        offset: readstat_off_t,
        whence: readstat_io_flags_t,
        io_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_off_t,
>;
pub type readstat_read_handler = ::std::option::Option<
    unsafe extern "C" fn(
        buf: *mut ::std::os::raw::c_void,
        nbyte: usize,
        io_ctx: *mut ::std::os::raw::c_void,
    ) -> isize,
>;
pub type readstat_update_handler = ::std::option::Option<
    unsafe extern "C" fn(
        file_size: ::std::os::raw::c_long,
        progress_handler: readstat_progress_handler,
        user_ctx: *mut ::std::os::raw::c_void,
        io_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_io_s {
    pub open: readstat_open_handler,
    pub close: readstat_close_handler,
    pub seek: readstat_seek_handler,
    pub read: readstat_read_handler,
    pub update: readstat_update_handler,
    pub io_ctx: *mut ::std::os::raw::c_void,
    pub io_ctx_needs_free: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_io_s"][::std::mem::size_of::<readstat_io_s>() - 56usize];
    ["Alignment of readstat_io_s"][::std::mem::align_of::<readstat_io_s>() - 8usize];
    ["Offset of field: readstat_io_s::open"][::std::mem::offset_of!(readstat_io_s, open) - 0usize];
    ["Offset of field: readstat_io_s::close"]
        [::std::mem::offset_of!(readstat_io_s, close) - 8usize];
    ["Offset of field: readstat_io_s::seek"][::std::mem::offset_of!(readstat_io_s, seek) - 16usize];
    ["Offset of field: readstat_io_s::read"][::std::mem::offset_of!(readstat_io_s, read) - 24usize];
    ["Offset of field: readstat_io_s::update"]
        [::std::mem::offset_of!(readstat_io_s, update) - 32usize];
    ["Offset of field: readstat_io_s::io_ctx"]
        [::std::mem::offset_of!(readstat_io_s, io_ctx) - 40usize];
    ["Offset of field: readstat_io_s::io_ctx_needs_free"]
        [::std::mem::offset_of!(readstat_io_s, io_ctx_needs_free) - 48usize];
};
pub type readstat_io_t = readstat_io_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_callbacks_s {
    pub metadata: readstat_metadata_handler,
    pub note: readstat_note_handler,
    pub variable: readstat_variable_handler,
    pub fweight: readstat_fweight_handler,
    pub value: readstat_value_handler,
    pub value_label: readstat_value_label_handler,
    pub error: readstat_error_handler,
    pub progress: readstat_progress_handler,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_callbacks_s"][::std::mem::size_of::<readstat_callbacks_s>() - 64usize];
    ["Alignment of readstat_callbacks_s"][::std::mem::align_of::<readstat_callbacks_s>() - 8usize];
    ["Offset of field: readstat_callbacks_s::metadata"]
        [::std::mem::offset_of!(readstat_callbacks_s, metadata) - 0usize];
    ["Offset of field: readstat_callbacks_s::note"]
        [::std::mem::offset_of!(readstat_callbacks_s, note) - 8usize];
    ["Offset of field: readstat_callbacks_s::variable"]
        [::std::mem::offset_of!(readstat_callbacks_s, variable) - 16usize];
    ["Offset of field: readstat_callbacks_s::fweight"]
        [::std::mem::offset_of!(readstat_callbacks_s, fweight) - 24usize];
    ["Offset of field: readstat_callbacks_s::value"]
        [::std::mem::offset_of!(readstat_callbacks_s, value) - 32usize];
    ["Offset of field: readstat_callbacks_s::value_label"]
        [::std::mem::offset_of!(readstat_callbacks_s, value_label) - 40usize];
    ["Offset of field: readstat_callbacks_s::error"]
        [::std::mem::offset_of!(readstat_callbacks_s, error) - 48usize];
    ["Offset of field: readstat_callbacks_s::progress"]
        [::std::mem::offset_of!(readstat_callbacks_s, progress) - 56usize];
};
pub type readstat_callbacks_t = readstat_callbacks_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_parser_s {
    pub handlers: readstat_callbacks_t,
    pub io: *mut readstat_io_t,
    pub input_encoding: *const ::std::os::raw::c_char,
    pub output_encoding: *const ::std::os::raw::c_char,
    pub row_limit: ::std::os::raw::c_long,
    pub row_offset: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_parser_s"][::std::mem::size_of::<readstat_parser_s>() - 104usize];
    ["Alignment of readstat_parser_s"][::std::mem::align_of::<readstat_parser_s>() - 8usize];
    ["Offset of field: readstat_parser_s::handlers"]
        [::std::mem::offset_of!(readstat_parser_s, handlers) - 0usize];
    ["Offset of field: readstat_parser_s::io"]
        [::std::mem::offset_of!(readstat_parser_s, io) - 64usize];
    ["Offset of field: readstat_parser_s::input_encoding"]
        [::std::mem::offset_of!(readstat_parser_s, input_encoding) - 72usize];
    ["Offset of field: readstat_parser_s::output_encoding"]
        [::std::mem::offset_of!(readstat_parser_s, output_encoding) - 80usize];
    ["Offset of field: readstat_parser_s::row_limit"]
        [::std::mem::offset_of!(readstat_parser_s, row_limit) - 88usize];
    ["Offset of field: readstat_parser_s::row_offset"]
        [::std::mem::offset_of!(readstat_parser_s, row_offset) - 96usize];
};
pub type readstat_parser_t = readstat_parser_s;
unsafe extern "C" {
    pub fn readstat_parser_init() -> *mut readstat_parser_t;
}
unsafe extern "C" {
    pub fn readstat_parser_free(parser: *mut readstat_parser_t);
}
unsafe extern "C" {
    pub fn readstat_io_free(io: *mut readstat_io_t);
}
unsafe extern "C" {
    pub fn readstat_set_metadata_handler(
        parser: *mut readstat_parser_t,
        metadata_handler: readstat_metadata_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_note_handler(
        parser: *mut readstat_parser_t,
        note_handler: readstat_note_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_variable_handler(
        parser: *mut readstat_parser_t,
        variable_handler: readstat_variable_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_fweight_handler(
        parser: *mut readstat_parser_t,
        fweight_handler: readstat_fweight_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_value_handler(
        parser: *mut readstat_parser_t,
        value_handler: readstat_value_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_value_label_handler(
        parser: *mut readstat_parser_t,
        value_label_handler: readstat_value_label_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_error_handler(
        parser: *mut readstat_parser_t,
        error_handler: readstat_error_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_progress_handler(
        parser: *mut readstat_parser_t,
        progress_handler: readstat_progress_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_open_handler(
        parser: *mut readstat_parser_t,
        open_handler: readstat_open_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_close_handler(
        parser: *mut readstat_parser_t,
        close_handler: readstat_close_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_seek_handler(
        parser: *mut readstat_parser_t,
        seek_handler: readstat_seek_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_read_handler(
        parser: *mut readstat_parser_t,
        read_handler: readstat_read_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_update_handler(
        parser: *mut readstat_parser_t,
        update_handler: readstat_update_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_io_ctx(
        parser: *mut readstat_parser_t,
        io_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_file_character_encoding(
        parser: *mut readstat_parser_t,
        encoding: *const ::std::os::raw::c_char,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_handler_character_encoding(
        parser: *mut readstat_parser_t,
        encoding: *const ::std::os::raw::c_char,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_row_limit(
        parser: *mut readstat_parser_t,
        row_limit: ::std::os::raw::c_long,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_set_row_offset(
        parser: *mut readstat_parser_t,
        row_offset: ::std::os::raw::c_long,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_parse_dta(
        parser: *mut readstat_parser_t,
        path: *const ::std::os::raw::c_char,
        user_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_parse_sav(
        parser: *mut readstat_parser_t,
        path: *const ::std::os::raw::c_char,
        user_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_parse_por(
        parser: *mut readstat_parser_t,
        path: *const ::std::os::raw::c_char,
        user_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_parse_sas7bdat(
        parser: *mut readstat_parser_t,
        path: *const ::std::os::raw::c_char,
        user_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_parse_sas7bcat(
        parser: *mut readstat_parser_t,
        path: *const ::std::os::raw::c_char,
        user_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_parse_xport(
        parser: *mut readstat_parser_t,
        path: *const ::std::os::raw::c_char,
        user_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_parse_sas_commands(
        parser: *mut readstat_parser_t,
        filepath: *const ::std::os::raw::c_char,
        user_ctx: *mut ::std::os::raw::c_void,
        outError: *mut readstat_error_t,
    ) -> *mut readstat_schema_t;
}
unsafe extern "C" {
    pub fn readstat_parse_spss_commands(
        parser: *mut readstat_parser_t,
        filepath: *const ::std::os::raw::c_char,
        user_ctx: *mut ::std::os::raw::c_void,
        outError: *mut readstat_error_t,
    ) -> *mut readstat_schema_t;
}
unsafe extern "C" {
    pub fn readstat_parse_stata_dictionary(
        parser: *mut readstat_parser_t,
        filepath: *const ::std::os::raw::c_char,
        user_ctx: *mut ::std::os::raw::c_void,
        outError: *mut readstat_error_t,
    ) -> *mut readstat_schema_t;
}
unsafe extern "C" {
    pub fn readstat_parse_txt(
        parser: *mut readstat_parser_t,
        filename: *const ::std::os::raw::c_char,
        schema: *mut readstat_schema_t,
        user_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_schema_free(schema: *mut readstat_schema_t);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_string_ref_s {
    pub first_v: i64,
    pub first_o: i64,
    pub len: usize,
    pub data: [::std::os::raw::c_char; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_string_ref_s"][::std::mem::size_of::<readstat_string_ref_s>() - 32usize];
    ["Alignment of readstat_string_ref_s"]
        [::std::mem::align_of::<readstat_string_ref_s>() - 8usize];
    ["Offset of field: readstat_string_ref_s::first_v"]
        [::std::mem::offset_of!(readstat_string_ref_s, first_v) - 0usize];
    ["Offset of field: readstat_string_ref_s::first_o"]
        [::std::mem::offset_of!(readstat_string_ref_s, first_o) - 8usize];
    ["Offset of field: readstat_string_ref_s::len"]
        [::std::mem::offset_of!(readstat_string_ref_s, len) - 16usize];
    ["Offset of field: readstat_string_ref_s::data"]
        [::std::mem::offset_of!(readstat_string_ref_s, data) - 24usize];
};
pub type readstat_string_ref_t = readstat_string_ref_s;
pub type readstat_variable_width_callback =
    ::std::option::Option<unsafe extern "C" fn(type_: readstat_type_t, user_width: usize) -> usize>;
pub type readstat_variable_ok_callback = ::std::option::Option<
    unsafe extern "C" fn(variable: *const readstat_variable_t) -> readstat_error_t,
>;
pub type readstat_write_int8_callback = ::std::option::Option<
    unsafe extern "C" fn(
        row_data: *mut ::std::os::raw::c_void,
        variable: *const readstat_variable_t,
        value: i8,
    ) -> readstat_error_t,
>;
pub type readstat_write_int16_callback = ::std::option::Option<
    unsafe extern "C" fn(
        row_data: *mut ::std::os::raw::c_void,
        variable: *const readstat_variable_t,
        value: i16,
    ) -> readstat_error_t,
>;
pub type readstat_write_int32_callback = ::std::option::Option<
    unsafe extern "C" fn(
        row_data: *mut ::std::os::raw::c_void,
        variable: *const readstat_variable_t,
        value: i32,
    ) -> readstat_error_t,
>;
pub type readstat_write_float_callback = ::std::option::Option<
    unsafe extern "C" fn(
        row_data: *mut ::std::os::raw::c_void,
        variable: *const readstat_variable_t,
        value: f32,
    ) -> readstat_error_t,
>;
pub type readstat_write_double_callback = ::std::option::Option<
    unsafe extern "C" fn(
        row_data: *mut ::std::os::raw::c_void,
        variable: *const readstat_variable_t,
        value: f64,
    ) -> readstat_error_t,
>;
pub type readstat_write_string_callback = ::std::option::Option<
    unsafe extern "C" fn(
        row_data: *mut ::std::os::raw::c_void,
        variable: *const readstat_variable_t,
        value: *const ::std::os::raw::c_char,
    ) -> readstat_error_t,
>;
pub type readstat_write_string_ref_callback = ::std::option::Option<
    unsafe extern "C" fn(
        row_data: *mut ::std::os::raw::c_void,
        variable: *const readstat_variable_t,
        ref_: *mut readstat_string_ref_t,
    ) -> readstat_error_t,
>;
pub type readstat_write_missing_callback = ::std::option::Option<
    unsafe extern "C" fn(
        row_data: *mut ::std::os::raw::c_void,
        variable: *const readstat_variable_t,
    ) -> readstat_error_t,
>;
pub type readstat_write_tagged_callback = ::std::option::Option<
    unsafe extern "C" fn(
        row_data: *mut ::std::os::raw::c_void,
        variable: *const readstat_variable_t,
        tag: ::std::os::raw::c_char,
    ) -> readstat_error_t,
>;
pub type readstat_begin_data_callback = ::std::option::Option<
    unsafe extern "C" fn(writer: *mut ::std::os::raw::c_void) -> readstat_error_t,
>;
pub type readstat_write_row_callback = ::std::option::Option<
    unsafe extern "C" fn(
        writer: *mut ::std::os::raw::c_void,
        row_data: *mut ::std::os::raw::c_void,
        row_len: usize,
    ) -> readstat_error_t,
>;
pub type readstat_end_data_callback = ::std::option::Option<
    unsafe extern "C" fn(writer: *mut ::std::os::raw::c_void) -> readstat_error_t,
>;
pub type readstat_module_ctx_free_callback =
    ::std::option::Option<unsafe extern "C" fn(module_ctx: *mut ::std::os::raw::c_void)>;
pub type readstat_metadata_ok_callback = ::std::option::Option<
    unsafe extern "C" fn(writer: *mut ::std::os::raw::c_void) -> readstat_error_t,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_writer_callbacks_s {
    pub variable_width: readstat_variable_width_callback,
    pub variable_ok: readstat_variable_ok_callback,
    pub write_int8: readstat_write_int8_callback,
    pub write_int16: readstat_write_int16_callback,
    pub write_int32: readstat_write_int32_callback,
    pub write_float: readstat_write_float_callback,
    pub write_double: readstat_write_double_callback,
    pub write_string: readstat_write_string_callback,
    pub write_string_ref: readstat_write_string_ref_callback,
    pub write_missing_string: readstat_write_missing_callback,
    pub write_missing_number: readstat_write_missing_callback,
    pub write_missing_tagged: readstat_write_tagged_callback,
    pub begin_data: readstat_begin_data_callback,
    pub write_row: readstat_write_row_callback,
    pub end_data: readstat_end_data_callback,
    pub module_ctx_free: readstat_module_ctx_free_callback,
    pub metadata_ok: readstat_metadata_ok_callback,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_writer_callbacks_s"]
        [::std::mem::size_of::<readstat_writer_callbacks_s>() - 136usize];
    ["Alignment of readstat_writer_callbacks_s"]
        [::std::mem::align_of::<readstat_writer_callbacks_s>() - 8usize];
    ["Offset of field: readstat_writer_callbacks_s::variable_width"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, variable_width) - 0usize];
    ["Offset of field: readstat_writer_callbacks_s::variable_ok"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, variable_ok) - 8usize];
    ["Offset of field: readstat_writer_callbacks_s::write_int8"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_int8) - 16usize];
    ["Offset of field: readstat_writer_callbacks_s::write_int16"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_int16) - 24usize];
    ["Offset of field: readstat_writer_callbacks_s::write_int32"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_int32) - 32usize];
    ["Offset of field: readstat_writer_callbacks_s::write_float"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_float) - 40usize];
    ["Offset of field: readstat_writer_callbacks_s::write_double"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_double) - 48usize];
    ["Offset of field: readstat_writer_callbacks_s::write_string"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_string) - 56usize];
    ["Offset of field: readstat_writer_callbacks_s::write_string_ref"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_string_ref) - 64usize];
    ["Offset of field: readstat_writer_callbacks_s::write_missing_string"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_missing_string) - 72usize];
    ["Offset of field: readstat_writer_callbacks_s::write_missing_number"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_missing_number) - 80usize];
    ["Offset of field: readstat_writer_callbacks_s::write_missing_tagged"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_missing_tagged) - 88usize];
    ["Offset of field: readstat_writer_callbacks_s::begin_data"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, begin_data) - 96usize];
    ["Offset of field: readstat_writer_callbacks_s::write_row"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, write_row) - 104usize];
    ["Offset of field: readstat_writer_callbacks_s::end_data"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, end_data) - 112usize];
    ["Offset of field: readstat_writer_callbacks_s::module_ctx_free"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, module_ctx_free) - 120usize];
    ["Offset of field: readstat_writer_callbacks_s::metadata_ok"]
        [::std::mem::offset_of!(readstat_writer_callbacks_s, metadata_ok) - 128usize];
};
pub type readstat_writer_callbacks_t = readstat_writer_callbacks_s;
pub type readstat_data_writer = ::std::option::Option<
    unsafe extern "C" fn(
        data: *const ::std::os::raw::c_void,
        len: usize,
        ctx: *mut ::std::os::raw::c_void,
    ) -> isize,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct readstat_writer_s {
    pub data_writer: readstat_data_writer,
    pub bytes_written: usize,
    pub version: ::std::os::raw::c_long,
    pub is_64bit: ::std::os::raw::c_int,
    pub compression: readstat_compress_t,
    pub timestamp: time_t,
    pub variables: *mut *mut readstat_variable_t,
    pub variables_count: ::std::os::raw::c_long,
    pub variables_capacity: ::std::os::raw::c_long,
    pub label_sets: *mut *mut readstat_label_set_t,
    pub label_sets_count: ::std::os::raw::c_long,
    pub label_sets_capacity: ::std::os::raw::c_long,
    pub notes: *mut *mut ::std::os::raw::c_char,
    pub notes_count: ::std::os::raw::c_long,
    pub notes_capacity: ::std::os::raw::c_long,
    pub string_refs: *mut *mut readstat_string_ref_t,
    pub string_refs_count: ::std::os::raw::c_long,
    pub string_refs_capacity: ::std::os::raw::c_long,
    pub row: *mut ::std::os::raw::c_uchar,
    pub row_len: usize,
    pub row_count: ::std::os::raw::c_int,
    pub current_row: ::std::os::raw::c_int,
    pub file_label: [::std::os::raw::c_char; 257usize],
    pub table_name: [::std::os::raw::c_char; 33usize],
    pub fweight_variable: *const readstat_variable_t,
    pub callbacks: readstat_writer_callbacks_t,
    pub error_handler: readstat_error_handler,
    pub module_ctx: *mut ::std::os::raw::c_void,
    pub user_ctx: *mut ::std::os::raw::c_void,
    pub initialized: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of readstat_writer_s"][::std::mem::size_of::<readstat_writer_s>() - 632usize];
    ["Alignment of readstat_writer_s"][::std::mem::align_of::<readstat_writer_s>() - 8usize];
    ["Offset of field: readstat_writer_s::data_writer"]
        [::std::mem::offset_of!(readstat_writer_s, data_writer) - 0usize];
    ["Offset of field: readstat_writer_s::bytes_written"]
        [::std::mem::offset_of!(readstat_writer_s, bytes_written) - 8usize];
    ["Offset of field: readstat_writer_s::version"]
        [::std::mem::offset_of!(readstat_writer_s, version) - 16usize];
    ["Offset of field: readstat_writer_s::is_64bit"]
        [::std::mem::offset_of!(readstat_writer_s, is_64bit) - 24usize];
    ["Offset of field: readstat_writer_s::compression"]
        [::std::mem::offset_of!(readstat_writer_s, compression) - 28usize];
    ["Offset of field: readstat_writer_s::timestamp"]
        [::std::mem::offset_of!(readstat_writer_s, timestamp) - 32usize];
    ["Offset of field: readstat_writer_s::variables"]
        [::std::mem::offset_of!(readstat_writer_s, variables) - 40usize];
    ["Offset of field: readstat_writer_s::variables_count"]
        [::std::mem::offset_of!(readstat_writer_s, variables_count) - 48usize];
    ["Offset of field: readstat_writer_s::variables_capacity"]
        [::std::mem::offset_of!(readstat_writer_s, variables_capacity) - 56usize];
    ["Offset of field: readstat_writer_s::label_sets"]
        [::std::mem::offset_of!(readstat_writer_s, label_sets) - 64usize];
    ["Offset of field: readstat_writer_s::label_sets_count"]
        [::std::mem::offset_of!(readstat_writer_s, label_sets_count) - 72usize];
    ["Offset of field: readstat_writer_s::label_sets_capacity"]
        [::std::mem::offset_of!(readstat_writer_s, label_sets_capacity) - 80usize];
    ["Offset of field: readstat_writer_s::notes"]
        [::std::mem::offset_of!(readstat_writer_s, notes) - 88usize];
    ["Offset of field: readstat_writer_s::notes_count"]
        [::std::mem::offset_of!(readstat_writer_s, notes_count) - 96usize];
    ["Offset of field: readstat_writer_s::notes_capacity"]
        [::std::mem::offset_of!(readstat_writer_s, notes_capacity) - 104usize];
    ["Offset of field: readstat_writer_s::string_refs"]
        [::std::mem::offset_of!(readstat_writer_s, string_refs) - 112usize];
    ["Offset of field: readstat_writer_s::string_refs_count"]
        [::std::mem::offset_of!(readstat_writer_s, string_refs_count) - 120usize];
    ["Offset of field: readstat_writer_s::string_refs_capacity"]
        [::std::mem::offset_of!(readstat_writer_s, string_refs_capacity) - 128usize];
    ["Offset of field: readstat_writer_s::row"]
        [::std::mem::offset_of!(readstat_writer_s, row) - 136usize];
    ["Offset of field: readstat_writer_s::row_len"]
        [::std::mem::offset_of!(readstat_writer_s, row_len) - 144usize];
    ["Offset of field: readstat_writer_s::row_count"]
        [::std::mem::offset_of!(readstat_writer_s, row_count) - 152usize];
    ["Offset of field: readstat_writer_s::current_row"]
        [::std::mem::offset_of!(readstat_writer_s, current_row) - 156usize];
    ["Offset of field: readstat_writer_s::file_label"]
        [::std::mem::offset_of!(readstat_writer_s, file_label) - 160usize];
    ["Offset of field: readstat_writer_s::table_name"]
        [::std::mem::offset_of!(readstat_writer_s, table_name) - 417usize];
    ["Offset of field: readstat_writer_s::fweight_variable"]
        [::std::mem::offset_of!(readstat_writer_s, fweight_variable) - 456usize];
    ["Offset of field: readstat_writer_s::callbacks"]
        [::std::mem::offset_of!(readstat_writer_s, callbacks) - 464usize];
    ["Offset of field: readstat_writer_s::error_handler"]
        [::std::mem::offset_of!(readstat_writer_s, error_handler) - 600usize];
    ["Offset of field: readstat_writer_s::module_ctx"]
        [::std::mem::offset_of!(readstat_writer_s, module_ctx) - 608usize];
    ["Offset of field: readstat_writer_s::user_ctx"]
        [::std::mem::offset_of!(readstat_writer_s, user_ctx) - 616usize];
    ["Offset of field: readstat_writer_s::initialized"]
        [::std::mem::offset_of!(readstat_writer_s, initialized) - 624usize];
};
pub type readstat_writer_t = readstat_writer_s;
unsafe extern "C" {
    pub fn readstat_writer_init() -> *mut readstat_writer_t;
}
unsafe extern "C" {
    pub fn readstat_set_data_writer(
        writer: *mut readstat_writer_t,
        data_writer: readstat_data_writer,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_add_label_set(
        writer: *mut readstat_writer_t,
        type_: readstat_type_t,
        name: *const ::std::os::raw::c_char,
    ) -> *mut readstat_label_set_t;
}
unsafe extern "C" {
    pub fn readstat_label_double_value(
        label_set: *mut readstat_label_set_t,
        value: f64,
        label: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn readstat_label_int32_value(
        label_set: *mut readstat_label_set_t,
        value: i32,
        label: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn readstat_label_string_value(
        label_set: *mut readstat_label_set_t,
        value: *const ::std::os::raw::c_char,
        label: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn readstat_label_tagged_value(
        label_set: *mut readstat_label_set_t,
        tag: ::std::os::raw::c_char,
        label: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn readstat_add_variable(
        writer: *mut readstat_writer_t,
        name: *const ::std::os::raw::c_char,
        type_: readstat_type_t,
        storage_width: usize,
    ) -> *mut readstat_variable_t;
}
unsafe extern "C" {
    pub fn readstat_variable_set_label(
        variable: *mut readstat_variable_t,
        label: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn readstat_variable_set_format(
        variable: *mut readstat_variable_t,
        format: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn readstat_variable_set_label_set(
        variable: *mut readstat_variable_t,
        label_set: *mut readstat_label_set_t,
    );
}
unsafe extern "C" {
    pub fn readstat_variable_set_measure(
        variable: *mut readstat_variable_t,
        measure: readstat_measure_t,
    );
}
unsafe extern "C" {
    pub fn readstat_variable_set_alignment(
        variable: *mut readstat_variable_t,
        alignment: readstat_alignment_t,
    );
}
unsafe extern "C" {
    pub fn readstat_variable_set_display_width(
        variable: *mut readstat_variable_t,
        display_width: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn readstat_variable_add_missing_double_value(
        variable: *mut readstat_variable_t,
        value: f64,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_variable_add_missing_double_range(
        variable: *mut readstat_variable_t,
        lo: f64,
        hi: f64,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_variable_add_missing_string_value(
        variable: *mut readstat_variable_t,
        value: *const ::std::os::raw::c_char,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_variable_add_missing_string_range(
        variable: *mut readstat_variable_t,
        lo: *const ::std::os::raw::c_char,
        hi: *const ::std::os::raw::c_char,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_get_variable(
        writer: *mut readstat_writer_t,
        index: ::std::os::raw::c_int,
    ) -> *mut readstat_variable_t;
}
unsafe extern "C" {
    pub fn readstat_add_note(writer: *mut readstat_writer_t, note: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn readstat_add_string_ref(
        writer: *mut readstat_writer_t,
        string: *const ::std::os::raw::c_char,
    ) -> *mut readstat_string_ref_t;
}
unsafe extern "C" {
    pub fn readstat_get_string_ref(
        writer: *mut readstat_writer_t,
        index: ::std::os::raw::c_int,
    ) -> *mut readstat_string_ref_t;
}
unsafe extern "C" {
    pub fn readstat_writer_set_file_label(
        writer: *mut readstat_writer_t,
        file_label: *const ::std::os::raw::c_char,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_writer_set_file_timestamp(
        writer: *mut readstat_writer_t,
        timestamp: time_t,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_writer_set_fweight_variable(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_writer_set_file_format_version(
        writer: *mut readstat_writer_t,
        file_format_version: u8,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_writer_set_table_name(
        writer: *mut readstat_writer_t,
        table_name: *const ::std::os::raw::c_char,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_writer_set_file_format_is_64bit(
        writer: *mut readstat_writer_t,
        is_64bit: ::std::os::raw::c_int,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_writer_set_compression(
        writer: *mut readstat_writer_t,
        compression: readstat_compress_t,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_writer_set_error_handler(
        writer: *mut readstat_writer_t,
        error_handler: readstat_error_handler,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_begin_writing_dta(
        writer: *mut readstat_writer_t,
        user_ctx: *mut ::std::os::raw::c_void,
        row_count: ::std::os::raw::c_long,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_begin_writing_por(
        writer: *mut readstat_writer_t,
        user_ctx: *mut ::std::os::raw::c_void,
        row_count: ::std::os::raw::c_long,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_begin_writing_sas7bcat(
        writer: *mut readstat_writer_t,
        user_ctx: *mut ::std::os::raw::c_void,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_begin_writing_sas7bdat(
        writer: *mut readstat_writer_t,
        user_ctx: *mut ::std::os::raw::c_void,
        row_count: ::std::os::raw::c_long,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_begin_writing_sav(
        writer: *mut readstat_writer_t,
        user_ctx: *mut ::std::os::raw::c_void,
        row_count: ::std::os::raw::c_long,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_begin_writing_xport(
        writer: *mut readstat_writer_t,
        user_ctx: *mut ::std::os::raw::c_void,
        row_count: ::std::os::raw::c_long,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_validate_metadata(writer: *mut readstat_writer_t) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_validate_variable(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_begin_row(writer: *mut readstat_writer_t) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_insert_int8_value(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
        value: i8,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_insert_int16_value(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
        value: i16,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_insert_int32_value(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
        value: i32,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_insert_float_value(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
        value: f32,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_insert_double_value(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
        value: f64,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_insert_string_value(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
        value: *const ::std::os::raw::c_char,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_insert_string_ref(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
        ref_: *mut readstat_string_ref_t,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_insert_missing_value(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_insert_tagged_missing_value(
        writer: *mut readstat_writer_t,
        variable: *const readstat_variable_t,
        tag: ::std::os::raw::c_char,
    ) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_end_row(writer: *mut readstat_writer_t) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_end_writing(writer: *mut readstat_writer_t) -> readstat_error_t;
}
unsafe extern "C" {
    pub fn readstat_writer_free(writer: *mut readstat_writer_t);
}
